// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using ProjetoBanco.API.Data;

#nullable disable

namespace ProjetoBanco.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260506010000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjetoBanco.API.Models.Agencia", b =>
                {
                    b.Property<int>("IdAgencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAgencia"));

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("NVARCHAR2(2)");

                    b.Property<string>("NomeAgencia")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)");

                    b.HasKey("IdAgencia");

                    b.ToTable("Agencias");
                });

            modelBuilder.Entity("ProjetoBanco.API.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgenciaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.Property<string>("TipoCliente")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("NVARCHAR2(2)");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaId");

                    b.ToTable("Clientes");

                    b.HasDiscriminator<string>("TipoCliente").HasValue("Cliente");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ProjetoBanco.API.Models.Produto", b =>
                {
                    b.Property<int>("IdProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProduto"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.Property<string>("TipoProduto")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("NVARCHAR2(21)");

                    b.HasKey("IdProduto");

                    b.ToTable("Produtos");

                    b.HasDiscriminator<string>("TipoProduto").HasValue("Produto");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ProjetoBanco.API.Models.Contratacao", b =>
                {
                    b.Property<int>("IdContratacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdContratacao"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<decimal?>("ValorSolicitado")
                        .HasColumnType("NUMBER(18,2)");

                    b.HasKey("IdContratacao");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("Contratacoes");
                });

            modelBuilder.Entity("ProjetoBanco.API.Models.PessoaFisica", b =>
                {
                    b.HasBaseType("ProjetoBanco.API.Models.Cliente");

                    b.Property<string>("CPF")
                        .HasMaxLength(14)
                        .HasColumnType("NVARCHAR2(14)");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasDiscriminator().HasValue("PF");
                });

            modelBuilder.Entity("ProjetoBanco.API.Models.PessoaJuridica", b =>
                {
                    b.HasBaseType("ProjetoBanco.API.Models.Cliente");

                    b.Property<string>("CNPJ")
                        .HasMaxLength(18)
                        .HasColumnType("NVARCHAR2(18)");

                    b.Property<string>("RazaoSocial")
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.HasDiscriminator().HasValue("PJ");
                });

            modelBuilder.Entity("ProjetoBanco.API.Models.Emprestimo", b =>
                {
                    b.HasBaseType("ProjetoBanco.API.Models.Produto");

                    b.Property<decimal?>("TaxaJuros")
                        .HasColumnType("NUMBER(5,2)");

                    b.Property<decimal?>("ValorMaximo")
                        .HasColumnType("NUMBER(18,2)");

                    b.Property<decimal?>("ValorMinimo")
                        .HasColumnType("NUMBER(18,2)");

                    b.HasDiscriminator().HasValue("Emprestimo");
                });

            modelBuilder.Entity("ProjetoBanco.API.Models.Cliente", b =>
                {
                    b.HasOne("ProjetoBanco.API.Models.Agencia", "Agencia")
                        .WithMany()
                        .HasForeignKey("AgenciaId");

                    b.Navigation("Agencia");
                });

            modelBuilder.Entity("ProjetoBanco.API.Models.Contratacao", b =>
                {
                    b.HasOne("ProjetoBanco.API.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetoBanco.API.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Produto");
                });
#pragma warning restore 612, 618
        }
    }
}
